#! /usr/bin/env perl

# Given a git repository and reference (branch|tag|sha1), get the archive url.

sub usage {
  print STDERR "Usage: ./archive-url <repo> <ref>";
  exit
}

$URL = $ARGV[0];
$REF = $ARGV[1];

if ($URL eq "" || $REF eq "") { usage }

$github_url    = 'https://%s/%s/archive/%s.tar.gz';
$bitbucket_url = 'https://%s/%s/get/%s.tar.gz';
$gitlab_url    = 'https://%s/%s/repository/archive.tar.gz?ref=%s';

$pattern = qr{
  ^
  (?:\w+://|git@) # scheme
  ([\w.-]+)       # host -> $1
  [:/]
  ([\w/-]*)       # path -> $2
  (?:\.git)?      # extension
  $
}x;

if ($URL =~ $pattern)
{
  if    ($1 eq 'github.com')    { printf($github_url,    $1, $2, $REF) }
  elsif ($1 eq 'bitbucket.org') { printf($bitbucket_url, $1, $2, $REF) }
  elsif ($1 eq 'gitlab.com')    { printf($gitlab_url,    $1, $2, $REF) }
}
